name: Deploy API to Azure

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore server

    - name: Build
      run: dotnet build server --configuration Release --no-restore

    - name: Publish
      run: dotnet publish server -c Release -o publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: YOUR_APP_SERVICE_NAME
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish
